// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentJournal.Data;

#nullable disable

namespace StudentJournal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentJournal.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StudentJournal.Data.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Высшая математика",
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Общая физика",
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Программирование и алгоритмы",
                            Name = "Информатика"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Общая химия",
                            Name = "Химия"
                        },
                        new
                        {
                            Id = 5,
                            Description = "История России и мира",
                            Name = "История"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Основы проектирования зданий",
                            Name = "Архитектура"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Основы графического и промышленного дизайна",
                            Name = "Дизайн"
                        });
                });

            modelBuilder.Entity("StudentJournal.Data.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Score = 86,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Score = 72,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Score = 76,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Score = 79,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Score = 53,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            Score = 56,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            Score = 77,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 1,
                            Score = 97,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 2,
                            Score = 87,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            Score = 55,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 4,
                            Score = 78,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 5,
                            Score = 61,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 6,
                            Score = 94,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 7,
                            Score = 70,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 1,
                            Score = 87,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 2,
                            Score = 67,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 3,
                            Score = 59,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 4,
                            Score = 51,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 5,
                            Score = 63,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 6,
                            Score = 93,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 7,
                            Score = 61,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 1,
                            Score = 63,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 2,
                            Score = 50,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 3,
                            Score = 100,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 4,
                            Score = 59,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 5,
                            Score = 50,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 6,
                            Score = 51,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 7,
                            Score = 62,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 1,
                            Score = 85,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 2,
                            Score = 92,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 3,
                            Score = 78,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 4,
                            Score = 88,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 5,
                            Score = 85,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 6,
                            Score = 58,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 7,
                            Score = 63,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 1,
                            Score = 55,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 2,
                            Score = 69,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 38,
                            CourseId = 3,
                            Score = 63,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 39,
                            CourseId = 4,
                            Score = 93,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 40,
                            CourseId = 5,
                            Score = 96,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 41,
                            CourseId = 6,
                            Score = 57,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 42,
                            CourseId = 7,
                            Score = 83,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 43,
                            CourseId = 1,
                            Score = 82,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 44,
                            CourseId = 2,
                            Score = 90,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 45,
                            CourseId = 3,
                            Score = 70,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 46,
                            CourseId = 4,
                            Score = 71,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 47,
                            CourseId = 5,
                            Score = 74,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 48,
                            CourseId = 6,
                            Score = 82,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 49,
                            CourseId = 7,
                            Score = 85,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 50,
                            CourseId = 1,
                            Score = 79,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 51,
                            CourseId = 2,
                            Score = 77,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 52,
                            CourseId = 3,
                            Score = 95,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 53,
                            CourseId = 4,
                            Score = 52,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 54,
                            CourseId = 5,
                            Score = 67,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 55,
                            CourseId = 6,
                            Score = 65,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 56,
                            CourseId = 7,
                            Score = 86,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 57,
                            CourseId = 1,
                            Score = 77,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 58,
                            CourseId = 2,
                            Score = 54,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 59,
                            CourseId = 3,
                            Score = 68,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 60,
                            CourseId = 4,
                            Score = 76,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 61,
                            CourseId = 5,
                            Score = 64,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 62,
                            CourseId = 6,
                            Score = 58,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 63,
                            CourseId = 7,
                            Score = 52,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 64,
                            CourseId = 1,
                            Score = 72,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 65,
                            CourseId = 2,
                            Score = 88,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 66,
                            CourseId = 3,
                            Score = 60,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 67,
                            CourseId = 4,
                            Score = 84,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 68,
                            CourseId = 5,
                            Score = 95,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 69,
                            CourseId = 6,
                            Score = 94,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 70,
                            CourseId = 7,
                            Score = 70,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 71,
                            CourseId = 1,
                            Score = 95,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 72,
                            CourseId = 2,
                            Score = 73,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 73,
                            CourseId = 3,
                            Score = 94,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 74,
                            CourseId = 4,
                            Score = 99,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 75,
                            CourseId = 5,
                            Score = 82,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 76,
                            CourseId = 6,
                            Score = 86,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 77,
                            CourseId = 7,
                            Score = 91,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 78,
                            CourseId = 1,
                            Score = 51,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 79,
                            CourseId = 2,
                            Score = 56,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 80,
                            CourseId = 3,
                            Score = 76,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 81,
                            CourseId = 4,
                            Score = 56,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 82,
                            CourseId = 5,
                            Score = 68,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 83,
                            CourseId = 6,
                            Score = 90,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 84,
                            CourseId = 7,
                            Score = 53,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 85,
                            CourseId = 1,
                            Score = 86,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 86,
                            CourseId = 2,
                            Score = 57,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 87,
                            CourseId = 3,
                            Score = 68,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 88,
                            CourseId = 4,
                            Score = 62,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 89,
                            CourseId = 5,
                            Score = 93,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 90,
                            CourseId = 6,
                            Score = 95,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 91,
                            CourseId = 7,
                            Score = 50,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 92,
                            CourseId = 1,
                            Score = 74,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 93,
                            CourseId = 2,
                            Score = 71,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 94,
                            CourseId = 3,
                            Score = 94,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 95,
                            CourseId = 4,
                            Score = 97,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 96,
                            CourseId = 5,
                            Score = 59,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 97,
                            CourseId = 6,
                            Score = 60,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 98,
                            CourseId = 7,
                            Score = 87,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 99,
                            CourseId = 1,
                            Score = 89,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 100,
                            CourseId = 2,
                            Score = 85,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 101,
                            CourseId = 3,
                            Score = 81,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 102,
                            CourseId = 4,
                            Score = 96,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 103,
                            CourseId = 5,
                            Score = 60,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 104,
                            CourseId = 6,
                            Score = 73,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 105,
                            CourseId = 7,
                            Score = 75,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 106,
                            CourseId = 1,
                            Score = 56,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 107,
                            CourseId = 2,
                            Score = 51,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 108,
                            CourseId = 3,
                            Score = 58,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 109,
                            CourseId = 4,
                            Score = 92,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 110,
                            CourseId = 5,
                            Score = 80,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 111,
                            CourseId = 6,
                            Score = 67,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 112,
                            CourseId = 7,
                            Score = 87,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 113,
                            CourseId = 1,
                            Score = 77,
                            StudentId = 17
                        },
                        new
                        {
                            Id = 114,
                            CourseId = 2,
                            Score = 89,
                            StudentId = 17
                        },
                        new
                        {
                            Id = 115,
                            CourseId = 3,
                            Score = 54,
                            StudentId = 17
                        },
                        new
                        {
                            Id = 116,
                            CourseId = 4,
                            Score = 100,
                            StudentId = 17
                        },
                        new
                        {
                            Id = 117,
                            CourseId = 5,
                            Score = 86,
                            StudentId = 17
                        },
                        new
                        {
                            Id = 118,
                            CourseId = 6,
                            Score = 65,
                            StudentId = 17
                        },
                        new
                        {
                            Id = 119,
                            CourseId = 7,
                            Score = 81,
                            StudentId = 17
                        },
                        new
                        {
                            Id = 120,
                            CourseId = 1,
                            Score = 91,
                            StudentId = 18
                        },
                        new
                        {
                            Id = 121,
                            CourseId = 2,
                            Score = 63,
                            StudentId = 18
                        },
                        new
                        {
                            Id = 122,
                            CourseId = 3,
                            Score = 89,
                            StudentId = 18
                        },
                        new
                        {
                            Id = 123,
                            CourseId = 4,
                            Score = 76,
                            StudentId = 18
                        },
                        new
                        {
                            Id = 124,
                            CourseId = 5,
                            Score = 88,
                            StudentId = 18
                        },
                        new
                        {
                            Id = 125,
                            CourseId = 6,
                            Score = 55,
                            StudentId = 18
                        },
                        new
                        {
                            Id = 126,
                            CourseId = 7,
                            Score = 90,
                            StudentId = 18
                        },
                        new
                        {
                            Id = 127,
                            CourseId = 1,
                            Score = 85,
                            StudentId = 19
                        },
                        new
                        {
                            Id = 128,
                            CourseId = 2,
                            Score = 85,
                            StudentId = 19
                        },
                        new
                        {
                            Id = 129,
                            CourseId = 3,
                            Score = 90,
                            StudentId = 19
                        },
                        new
                        {
                            Id = 130,
                            CourseId = 4,
                            Score = 52,
                            StudentId = 19
                        },
                        new
                        {
                            Id = 131,
                            CourseId = 5,
                            Score = 50,
                            StudentId = 19
                        },
                        new
                        {
                            Id = 132,
                            CourseId = 6,
                            Score = 95,
                            StudentId = 19
                        },
                        new
                        {
                            Id = 133,
                            CourseId = 7,
                            Score = 82,
                            StudentId = 19
                        },
                        new
                        {
                            Id = 134,
                            CourseId = 1,
                            Score = 78,
                            StudentId = 20
                        },
                        new
                        {
                            Id = 135,
                            CourseId = 2,
                            Score = 77,
                            StudentId = 20
                        },
                        new
                        {
                            Id = 136,
                            CourseId = 3,
                            Score = 90,
                            StudentId = 20
                        },
                        new
                        {
                            Id = 137,
                            CourseId = 4,
                            Score = 94,
                            StudentId = 20
                        },
                        new
                        {
                            Id = 138,
                            CourseId = 5,
                            Score = 69,
                            StudentId = 20
                        },
                        new
                        {
                            Id = 139,
                            CourseId = 6,
                            Score = 91,
                            StudentId = 20
                        },
                        new
                        {
                            Id = 140,
                            CourseId = 7,
                            Score = 64,
                            StudentId = 20
                        });
                });

            modelBuilder.Entity("StudentJournal.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Group = "ИИПБ-24-1",
                            Institute = "Строительный институт",
                            Name = "Иван Иванов"
                        },
                        new
                        {
                            Id = 2,
                            Group = "ВШЦТ-24-1",
                            Institute = "Высшая школа цифровых технологий",
                            Name = "Мария Петрова"
                        },
                        new
                        {
                            Id = 3,
                            Group = "ТИ-24-2",
                            Institute = "Технологический институт",
                            Name = "Алексей Смирнов"
                        },
                        new
                        {
                            Id = 4,
                            Group = "ИАД-24-1",
                            Institute = "Институт архитектуры и дизайна",
                            Name = "Екатерина Кузнецова"
                        },
                        new
                        {
                            Id = 5,
                            Group = "ИС-24-2",
                            Institute = "Институт сервиса",
                            Name = "Дмитрий Соколов"
                        },
                        new
                        {
                            Id = 6,
                            Group = "ИИПБ-24-2",
                            Institute = "Строительный институт",
                            Name = "Анна Попова"
                        },
                        new
                        {
                            Id = 7,
                            Group = "ВШЦТ-24-2",
                            Institute = "Высшая школа цифровых технологий",
                            Name = "Сергей Лебедев"
                        },
                        new
                        {
                            Id = 8,
                            Group = "ТИ-24-1",
                            Institute = "Технологический институт",
                            Name = "Ольга Морозова"
                        },
                        new
                        {
                            Id = 9,
                            Group = "ИАД-24-2",
                            Institute = "Институт архитектуры и дизайна",
                            Name = "Никита Павлов"
                        },
                        new
                        {
                            Id = 10,
                            Group = "ИС-24-1",
                            Institute = "Институт сервиса",
                            Name = "Елена Васильева"
                        },
                        new
                        {
                            Id = 11,
                            Group = "ИИПБ-24-3",
                            Institute = "Строительный институт",
                            Name = "Максим Федоров"
                        },
                        new
                        {
                            Id = 12,
                            Group = "ВШЦТ-24-3",
                            Institute = "Высшая школа цифровых технологий",
                            Name = "Алина Михайлова"
                        },
                        new
                        {
                            Id = 13,
                            Group = "ТИ-24-3",
                            Institute = "Технологический институт",
                            Name = "Игорь Новиков"
                        },
                        new
                        {
                            Id = 14,
                            Group = "ИАД-24-3",
                            Institute = "Институт архитектуры и дизайна",
                            Name = "Светлана Семенова"
                        },
                        new
                        {
                            Id = 15,
                            Group = "ИС-24-3",
                            Institute = "Институт сервиса",
                            Name = "Владимир Егоров"
                        },
                        new
                        {
                            Id = 16,
                            Group = "ИИПБ-24-4",
                            Institute = "Строительный институт",
                            Name = "Татьяна Крылова"
                        },
                        new
                        {
                            Id = 17,
                            Group = "ВШЦТ-24-4",
                            Institute = "Высшая школа цифровых технологий",
                            Name = "Роман Николаев"
                        },
                        new
                        {
                            Id = 18,
                            Group = "ТИ-24-4",
                            Institute = "Технологический институт",
                            Name = "Марина Орлова"
                        },
                        new
                        {
                            Id = 19,
                            Group = "ИАД-24-4",
                            Institute = "Институт архитектуры и дизайна",
                            Name = "Павел Козлов"
                        },
                        new
                        {
                            Id = 20,
                            Group = "ИС-24-4",
                            Institute = "Институт сервиса",
                            Name = "Юлия Белова"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StudentJournal.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StudentJournal.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentJournal.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StudentJournal.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentJournal.Data.Models.Grade", b =>
                {
                    b.HasOne("StudentJournal.Data.Models.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentJournal.Data.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentJournal.Data.Models.Course", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("StudentJournal.Data.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
